### ISSUE TITLE
`t_rlog_dirty_operations` test possibly flaky?

### ISSUE THREAD

**Issue by thalesmg** [emqx/mria#46]
Apparently, this test is failing on CI occasionally.

It seems that the RLOG agent is dying with reason `shutdown` while in the normal state twice in a failing run.

For the same commit:

- [Example of successful run](https://github.com/emqx/mria/runs/4381120195)
- [Example of failed run](https://github.com/emqx/mria/actions/runs/1525711081)
- https://github.com/emqx/mria/runs/5278750333?check_suite_focus=true#step:8:5653

Logs from failures: 
[failure_logs.zip](https://github.com/emqx/mria/files/7633869/failure_logs.zip)

**Comment by ieQu1** [comment]
Very old issue, both code and tests have changed ever since.
