### ISSUE TITLE
mria_mnesia:running_nodes() should have a timeout.

### ISSUE THREAD

**Issue by k32** [emqx/mria#49]
mria_node_monitor process may end up stuck if the `mria_mnesia:running_nodes` function doesn't return in time.

**Comment by thalesmg** [comment]
Example of message accumulation when stuck in said multicall (apparently happened after one of the nodes died during a test):

![image](https://user-images.githubusercontent.com/16166434/146012399-c01ae1d8-e5c8-4bdb-9f0a-c2b848d0d1d5.png)
